server:
  port: 8080
spring:
  application:
    name: "RetoPichincha"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  datasource:
    url: "jdbc:postgresql://localhost:5432/reto-bancario"
    username: "postgres"
    password: "postgres"
    driverClassName: "org.postgresql.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
      properties:
        hibernate:
          format-sql: true
    show-sql: true
